version: "3"

services:
  kgalleryapi:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    container_name: kgallery-api-go
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - kgallery
    stdin_open: true 
    tty: true
  kgallerydb:
    image: postgres:15
    hostname: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kgallery
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data:z
    container_name: kgallery-db
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - kgallery
  # migrate:
  #   image: migrate/migrate
  #   networks:
  #     - kgallery
  #   volumes:
  #     - .:/migrations
  #   command: ["make migrate-up"]
  #   links: 
  #     - kgallerydb
networks:
  kgallery:
    driver: bridge
